"""Added user relationship to message queue table

Revision ID: 015458303462
Revises: 812e0c24715d
Create Date: 2024-01-11 21:03:12.102623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015458303462'
down_revision = '812e0c24715d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_queue', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message_queue', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_queue', type_='foreignkey')
    op.drop_column('message_queue', 'user_id')
    # ### end Alembic commands ###
