"""Added sender to MessageQueue

Revision ID: 0eca86215146
Revises: 6c19bf39240c
Create Date: 2024-01-11 17:37:07.006636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eca86215146'
down_revision = '6c19bf39240c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_queue', sa.Column('sender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_queue', 'sender')
    # ### end Alembic commands ###
