"""Switched team.tills to dynamic

Revision ID: 1beb194e4d1d
Revises: 05d5aaa16652
Create Date: 2020-11-10 09:35:21.615958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1beb194e4d1d'
down_revision = '05d5aaa16652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
