"""added wager relationship to team

Revision ID: 1e4fb2044126
Revises: bd370ef54762
Create Date: 2020-10-27 20:50:24.224131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4fb2044126'
down_revision = 'bd370ef54762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
