"""Added CompletedTasks table

Revision ID: 250a80761aee
Revises: 4fa2e6510158
Create Date: 2024-01-06 16:20:12.623103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250a80761aee'
down_revision = '4fa2e6510158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_tasks')
    # ### end Alembic commands ###
