"""Added Local Table

Revision ID: 284bc12bd7e6
Revises: b65ffbaf39e8
Create Date: 2020-10-28 19:29:12.301916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284bc12bd7e6'
down_revision = 'b65ffbaf39e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('local')
    # ### end Alembic commands ###
