"""change u.wagers to u.bets

Revision ID: 4d9e6fd1bf35
Revises: 584e57f03df3
Create Date: 2020-10-27 20:24:11.320479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9e6fd1bf35'
down_revision = '584e57f03df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
