"""Added team to Completed Task Table

Revision ID: 50a4e90b32d5
Revises: 250a80761aee
Create Date: 2024-01-06 16:28:30.023236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a4e90b32d5'
down_revision = '250a80761aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_tasks', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'completed_tasks', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'completed_tasks', type_='foreignkey')
    op.drop_column('completed_tasks', 'team_id')
    # ### end Alembic commands ###
