"""change u.wagers to u.bets

Revision ID: 584e57f03df3
Revises: 8092291627e8
Create Date: 2020-10-27 20:21:23.230008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584e57f03df3'
down_revision = '8092291627e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
