"""Order Wagers by ID

Revision ID: 6d3f15e229a4
Revises: ee8952a054f5
Create Date: 2020-11-07 20:11:52.169249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3f15e229a4'
down_revision = 'ee8952a054f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
