"""Add Team to Points Table

Revision ID: 71986822288d
Revises: faf8c689c02c
Create Date: 2020-10-27 01:35:35.107710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71986822288d'
down_revision = 'faf8c689c02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'point', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'point', type_='foreignkey')
    op.drop_column('point', 'team_id')
    # ### end Alembic commands ###
