"""change u.wagers to u.bets

Revision ID: 8092291627e8
Revises: ec1422aa30b6
Create Date: 2020-10-27 20:19:46.917607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8092291627e8'
down_revision = 'ec1422aa30b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
