"""Added ip

Revision ID: 812e0c24715d
Revises: 0eca86215146
Create Date: 2024-01-11 17:52:54.247121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812e0c24715d'
down_revision = '0eca86215146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_queue', sa.Column('ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_queue', 'ip')
    # ### end Alembic commands ###
