"""Order Wagers by ID

Revision ID: 97306ac2eb77
Revises: 6d3f15e229a4
Create Date: 2020-11-07 20:12:29.200924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97306ac2eb77'
down_revision = '6d3f15e229a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
