"""fix messages relationship

Revision ID: af722e6e50bb
Revises: 889e5cb3676c
Create Date: 2020-10-29 15:54:23.982765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af722e6e50bb'
down_revision = '889e5cb3676c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
