"""Add dynamic to local

Revision ID: b074be8f8a4f
Revises: e64a019a8219
Create Date: 2020-10-28 22:39:40.373812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b074be8f8a4f'
down_revision = 'e64a019a8219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
