"""Change time format on wagers

Revision ID: b65ffbaf39e8
Revises: 1e4fb2044126
Create Date: 2020-10-27 22:35:09.396070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65ffbaf39e8'
down_revision = '1e4fb2044126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
