"""added potion to bets

Revision ID: bd370ef54762
Revises: 4d9e6fd1bf35
Create Date: 2020-10-27 20:36:30.214177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd370ef54762'
down_revision = '4d9e6fd1bf35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('position', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet', 'position')
    # ### end Alembic commands ###
