"""Add timestamps to local table

Revision ID: e64a019a8219
Revises: 284bc12bd7e6
Create Date: 2020-10-28 19:48:23.453003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64a019a8219'
down_revision = '284bc12bd7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('local', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local', 'updated_at')
    op.drop_column('local', 'created_at')
    # ### end Alembic commands ###
