"""Sort tills by date

Revision ID: e8a7a141ca31
Revises: 1beb194e4d1d
Create Date: 2020-11-10 12:55:54.788384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a7a141ca31'
down_revision = '1beb194e4d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
