"""add link to Teams and since

Revision ID: ede7e5abc36e
Revises: a4dc401b5086
Create Date: 2025-01-20 16:48:19.457043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede7e5abc36e'
down_revision = 'a4dc401b5086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
