"""Set Unique Constraint

Revision ID: faf8c689c02c
Revises: a0803947ba6b
Create Date: 2020-10-27 00:35:05.177758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf8c689c02c'
down_revision = 'a0803947ba6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'team', ['name'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'team', type_='unique')
    # ### end Alembic commands ###
