def get_characters():

    characters = ['beavis.zen',
                  'bong',
                  'bud-frogs',
                  'bunny',
                  'capybara',
                  'cheese',
                  'cower',
                  'daemon',
                  'default',
                  'dragon-and-cow',
                  'dragon',
                  'elephant-in-snake',
                  'elephant',
                  'eyes',
                  'flaming-sheep',
                  'ghostbusters',
                  'head-in',
                  'hellokitty',
                  'kiss',
                  'kitty',
                  'koala',
                  'kosh',
                  'luke-koala',
                  'mech-and-cow',
                  'meow',
                  'milk',
                  'moofasa',
                  'moose',
                  'mutilated',
                  'owl',
                  'ren',
                  'satanic',
                  'sheep',
                  'skeleton',
                  'small',
                  'sodomized',
                  'stegosaurus',
                  'stimpy',
                  'supermilker',
                  'surgery',
                  'telebears',
                  'three-eyes',
                  'turkey',
                  'turtle',
                  'tux',
                  'udder',
                  'vader-koala',
                  'vader',
                  'www', ]

    return characters
